export const projectOptions = [
  { value: '49', title: 'Internal' },
  { value: '108', title: '[APPMAN] MAC' },
  { value: '88', title: '[APPMAN] - AGM Life- Indo' },
  { value: '107', title: '[APPMAN] RPA' },
  { value: '122', title: '[APPMAN] The world eats ML' },
  { value: '235', title: '[Chubb] ILP' },
  { value: '102', title: 'Infra Team' },
  { value: '49', title: 'Internal' },
  { value: '50', title: 'ISO 27001' },
  { value: '132', title: 'MAC-KTAXA' },
  { value: '51', title: '[KTAXA] Advisor Zone' },
  { value: '48', title: 'On Bench' },
  { value: '91', title: '[Sales] AgentMate' },
  { value: '93', title: '[Sales] Enchancement' },
  { value: '94', title: '[Sales] MA' },
  { value: '92', title: '[Sales] SaaS' },
  { value: '130', title: '[SLI] Warranty' },
  { value: '106', title: '[Squad] All' },
  { value: '120', title: '[Squad] EA' },
  { value: '119', title: '[Squad] EQ' },
  { value: '121', title: '[Squad] ILP' },
  { value: '127', title: '[Squad] iPaaS' },
  { value: '123', title: '[Support] Support' },
  { value: '42', title: '[SVL] AgentMate SaaS' },
  { value: '44', title: '[TOKIO] Fast Track' },
]
