export const projectOptions = [
  { value: 108, label: '[APPMAN] MAC' },
  { value: 88, label: '[APPMAN] - AGM Life- Indo' },
  { value: 107, label: '[APPMAN] RPA' },
  { value: 122, label: '[APPMAN] The world eats ML' },
  { value: 235, label: '[Chubb] ILP' },
  { value: 102, label: 'Infra Team' },
  { value: 49, label: 'Internal' },
  { value: 50, label: 'ISO 27001' },
  { value: 132, label: 'MAC-KTAXA' },
  { value: 51, label: '[KTAXA] Advisor Zone' },
  { value: 48, label: 'On Bench' },
  { value: 91, label: '[Sales] AgentMate' },
  { value: 93, label: '[Sales] Enchancement' },
  { value: 94, label: '[Sales] MA' },
  { value: 92, label: '[Sales] SaaS' },
  { value: 130, label: '[SLI] Warranty' },
  { value: 106, label: '[Squad] All' },
  { value: 120, label: '[Squad] EA' },
  { value: 119, label: '[Squad] EQ' },
  { value: 121, label: '[Squad] ILP' },
  { value: 127, label: '[Squad] iPaaS' },
  { value: 123, label: '[Support] Support' },
  { value: 42, label: '[SVL] AgentMate SaaS' },
  { value: 44, label: '[TOKIO] Fast Track' },
]
